/**
 * AI Knowledge Generation Types
 * TypeScript types for AI-powered knowledge base article and FAQ generation
 */

/** Types of knowledge entries that can be generated */
export type KnowledgeEntryType = 
  | 'FAQ'
  | 'Product'
  | 'Service'
  | 'Policy'
  | 'Troubleshooting'
  | 'CaseStudy';

/** Request to generate a knowledge base article using AI */
export interface KnowledgeGenerationRequest {
  /** Topic or subject for the article */
  topic: string;
  /** Type of knowledge entry to generate */
  entryType: KnowledgeEntryType;
  /** Optional context or background information */
  context?: string;
  /** Desired tone (professional, friendly, technical) */
  tone?: string;
  /** Category for the generated article */
  category?: string;
  /** Optional keywords to include */
  keywords?: string[];
  /** Whether to generate related FAQs */
  generateRelatedFaqs?: boolean;
  /** Maximum number of related FAQs to generate */
  maxRelatedFaqs?: number;
}

/** Result of AI knowledge article generation */
export interface KnowledgeArticleResult {
  /** Whether the generation was successful */
  success: boolean;
  /** Error message if generation failed */
  errorMessage?: string;
  /** Whether the failure was due to usage limits */
  limitExceeded: boolean;
  /** Generated article title */
  title: string;
  /** Generated article content (markdown formatted) */
  content: string;
  /** Article category */
  category?: string;
  /** Suggested tags for the article */
  suggestedTags: string[];
  /** Suggested keywords for AI matching */
  suggestedKeywords: string[];
  /** Related FAQs if requested */
  relatedFaqs: FaqSuggestion[];
  /** Audit ID for feedback tracking */
  auditId?: string;
  /** Number of tokens used */
  tokensUsed: number;
  /** Generation timestamp */
  generatedAt: string;
}

/** A suggested FAQ entry extracted from conversations or generated by AI */
export interface FaqSuggestion {
  /** The FAQ question */
  question: string;
  /** The FAQ answer */
  answer: string;
  /** Suggested category */
  category?: string;
  /** Confidence score (0-100) */
  confidence: number;
  /** Source (e.g., "extracted_from_conversations", "ai_generated") */
  source: string;
}

/** Request for extracting FAQs from conversation history */
export interface ExtractFaqsRequest {
  /** Number of days of conversations to analyze */
  daysToAnalyze?: number;
  /** Maximum number of FAQs to extract */
  maxFaqs?: number;
  /** Minimum confidence threshold (0-100) */
  minConfidence?: number;
  /** Optional category filter for conversations */
  categoryFilter?: string;
}

/** Result of FAQ extraction from conversations */
export interface ExtractFaqsResult {
  /** Whether the extraction was successful */
  success: boolean;
  /** Error message if extraction failed */
  errorMessage?: string;
  /** Whether the failure was due to usage limits */
  limitExceeded: boolean;
  /** Extracted FAQ suggestions */
  faqs: FaqSuggestion[];
  /** Number of conversations analyzed */
  conversationsAnalyzed: number;
  /** Audit ID for feedback tracking */
  auditId?: string;
  /** Number of tokens used */
  tokensUsed: number;
  /** Extraction timestamp */
  extractedAt: string;
}

/** Generation mode for the AI Knowledge dialog */
export type KnowledgeGenerationMode = 'generate' | 'extract';

/** Tone options for content generation */
export const KNOWLEDGE_TONES = [
  { value: 'professional', label: 'Professional' },
  { value: 'friendly', label: 'Friendly' },
  { value: 'technical', label: 'Technical' },
  { value: 'casual', label: 'Casual' },
] as const;

/** Entry type options with descriptions */
export const KNOWLEDGE_ENTRY_TYPES: { value: KnowledgeEntryType; label: string; description: string }[] = [
  { value: 'FAQ', label: 'FAQ', description: 'Frequently asked question with answer' },
  { value: 'Product', label: 'Product Info', description: 'Product description and details' },
  { value: 'Service', label: 'Service Info', description: 'Service offerings and benefits' },
  { value: 'Policy', label: 'Policy', description: 'Company policies and procedures' },
  { value: 'Troubleshooting', label: 'Troubleshooting', description: 'Problem-solving guide' },
  { value: 'CaseStudy', label: 'Case Study', description: 'Customer success story' },
];

