namespace QualiFlow.Application.Features.Analytics.DTOs;

/// <summary>
/// Represents agent performance metrics.
/// </summary>
public record AgentPerformanceDto
{
    /// <summary>
    /// Gets the agent's user ID.
    /// </summary>
    public required Guid AgentId { get; init; }

    /// <summary>
    /// Gets the agent's full name.
    /// </summary>
    public required string AgentName { get; init; }

    /// <summary>
    /// Gets the total number of leads assigned to this agent.
    /// </summary>
    public required int TotalLeadsAssigned { get; init; }

    /// <summary>
    /// Gets the number of qualified leads.
    /// </summary>
    public required int QualifiedLeads { get; init; }

    /// <summary>
    /// Gets the number of converted leads.
    /// </summary>
    public required int ConvertedLeads { get; init; }

    /// <summary>
    /// Gets the total number of conversations handled.
    /// </summary>
    public required int TotalConversations { get; init; }

    /// <summary>
    /// Gets the total number of messages sent.
    /// </summary>
    public required int TotalMessagesSent { get; init; }

    /// <summary>
    /// Gets the average response time.
    /// </summary>
    public required TimeSpan AverageResponseTime { get; init; }

    /// <summary>
    /// Gets the conversion rate (percentage).
    /// </summary>
    public required decimal ConversionRate { get; init; }

    /// <summary>
    /// Gets the total revenue generated by this agent.
    /// </summary>
    public required decimal TotalRevenue { get; init; }

    /// <summary>
    /// Gets the average deal value.
    /// </summary>
    public required decimal AverageDealValue { get; init; }
}

