using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using QualiFlow.Application.Common.Interfaces;
using QualiFlow.Domain.Entities;
using QualiFlow.Infrastructure.Data;

namespace QualiFlow.Infrastructure.Repositories;

/// <summary>
/// Repository implementation for OnboardingProgress entity operations.
/// Multi-tenancy is enforced automatically via EF Core global query filters.
/// All queries are automatically filtered by the current user's BusinessId.
/// </summary>
/// <param name="context">The database context.</param>
/// <param name="currentUserService">Service for accessing current user context.</param>
/// <param name="logger">The logger instance.</param>
public partial class OnboardingRepository(
    QualiFlowDbContext context,
    ICurrentUserService currentUserService,
    ILogger<OnboardingRepository> logger) : IOnboardingRepository
{
    /// <inheritdoc />
    public Task<OnboardingProgress?> GetByBusinessIdAsync(
        Guid businessId,
        CancellationToken cancellationToken = default)
    {
        LogGettingOnboardingProgress(logger, businessId);

        // Note: We look for any record including soft-deleted ones
        // because the business_id has a unique constraint.
        // If soft-deleted, we'll restore it instead of creating a new one.
        return context.OnboardingProgress
            .IgnoreQueryFilters() // Bypass the global soft-delete filter
            .AsNoTracking()
            .Where(op => op.BusinessId == businessId)
            .FirstOrDefaultAsync(cancellationToken);
    }

    /// <inheritdoc />
    public async Task<OnboardingProgress> CreateAsync(
        OnboardingProgress progress,
        CancellationToken cancellationToken = default)
    {
        var businessId = currentUserService.GetBusinessId();
        LogCreatingOnboardingProgress(logger, businessId);

        await context.OnboardingProgress.AddAsync(progress, cancellationToken);
        await context.SaveChangesAsync(cancellationToken);

        return progress;
    }

    /// <inheritdoc />
    public async Task<OnboardingProgress> UpdateAsync(
        OnboardingProgress progress,
        CancellationToken cancellationToken = default)
    {
        var businessId = currentUserService.GetBusinessId();
        LogUpdatingOnboardingProgress(logger, progress.Id, businessId);

        // Attach the entity if it's not being tracked
        var entry = context.Entry(progress);
        if (entry.State == Microsoft.EntityFrameworkCore.EntityState.Detached)
        {
            context.OnboardingProgress.Attach(progress);
            entry.State = Microsoft.EntityFrameworkCore.EntityState.Modified;
        }

        await context.SaveChangesAsync(cancellationToken);

        return progress;
    }

    /// <inheritdoc />
    public async Task<bool> IsOnboardingCompleteAsync(
        Guid businessId,
        CancellationToken cancellationToken = default)
    {
        LogCheckingOnboardingComplete(logger, businessId);

        var progress = await context.OnboardingProgress
            .AsNoTracking()
            .Where(op => op.BusinessId == businessId && op.DeletedAt == null)
            .FirstOrDefaultAsync(cancellationToken);

        return progress?.IsComplete ?? false;
    }

    /// <inheritdoc />
    public Task<OnboardingProgress?> GetByBookingUidAsync(
        string bookingUid,
        CancellationToken cancellationToken = default)
    {
        LogGettingOnboardingProgressByBookingUid(logger, bookingUid);

        // Bypass multi-tenancy filters as this is called from webhooks
        return context.OnboardingProgress
            .IgnoreQueryFilters()
            .Where(op => op.OnboardingCallBookingUid == bookingUid && op.DeletedAt == null)
            .FirstOrDefaultAsync(cancellationToken);
    }

    // ============================================================================
    // Logging Methods (Generated by Source Generator)
    // ============================================================================

    [LoggerMessage(
        EventId = 5001,
        Level = LogLevel.Information,
        Message = "Getting onboarding progress for business {BusinessId}")]
    private static partial void LogGettingOnboardingProgress(ILogger logger, Guid businessId);

    [LoggerMessage(
        EventId = 5002,
        Level = LogLevel.Information,
        Message = "Creating onboarding progress for business {BusinessId}")]
    private static partial void LogCreatingOnboardingProgress(ILogger logger, Guid businessId);

    [LoggerMessage(
        EventId = 5003,
        Level = LogLevel.Information,
        Message = "Updating onboarding progress {ProgressId} for business {BusinessId}")]
    private static partial void LogUpdatingOnboardingProgress(ILogger logger, Guid progressId, Guid businessId);

    [LoggerMessage(
        EventId = 5004,
        Level = LogLevel.Information,
        Message = "Checking if onboarding is complete for business {BusinessId}")]
    private static partial void LogCheckingOnboardingComplete(ILogger logger, Guid businessId);

    [LoggerMessage(
        EventId = 5005,
        Level = LogLevel.Information,
        Message = "Getting onboarding progress by booking UID {BookingUid}")]
    private static partial void LogGettingOnboardingProgressByBookingUid(ILogger logger, string bookingUid);
}
