// -----------------------------------------------------------------------
// <copyright file="KnowledgeGenerationRequest.cs" company="QualiFlow">
//     Copyright (c) QualiFlow. All rights reserved.
// </copyright>
// -----------------------------------------------------------------------

using QualiFlow.Domain.Enums;

namespace QualiFlow.Application.Features.AI.DTOs;

/// <summary>
/// Request for generating a knowledge base article using AI.
/// </summary>
public sealed record KnowledgeGenerationRequest
{
    /// <summary>Gets the topic or subject for the article.</summary>
    public string Topic { get; init; } = string.Empty;

    /// <summary>Gets the type of knowledge entry to generate.</summary>
    public KnowledgeEntryType EntryType { get; init; } = KnowledgeEntryType.FAQ;

    /// <summary>Gets optional context or background information.</summary>
    public string? Context { get; init; }

    /// <summary>Gets the desired tone (professional, friendly, technical).</summary>
    public string Tone { get; init; } = "professional";

    /// <summary>Gets the category for the generated article.</summary>
    public string? Category { get; init; }

    /// <summary>Gets optional keywords to include.</summary>
    public IReadOnlyList<string>? Keywords { get; init; }

    /// <summary>Gets a value indicating whether to generate related FAQs.</summary>
    public bool GenerateRelatedFaqs { get; init; } = true;

    /// <summary>Gets the maximum number of related FAQs to generate.</summary>
    public int MaxRelatedFaqs { get; init; } = 3;
}

/// <summary>
/// Result of AI knowledge article generation.
/// </summary>
public sealed record KnowledgeArticleResult
{
    /// <summary>Gets a value indicating whether the generation was successful.</summary>
    public bool Success { get; init; }

    /// <summary>Gets the error message if generation failed.</summary>
    public string? ErrorMessage { get; init; }

    /// <summary>Gets a value indicating whether the failure was due to usage limits.</summary>
    public bool LimitExceeded { get; init; }

    /// <summary>Gets the generated article title.</summary>
    public string Title { get; init; } = string.Empty;

    /// <summary>Gets the generated article content (markdown formatted).</summary>
    public string Content { get; init; } = string.Empty;

    /// <summary>Gets the article category.</summary>
    public string? Category { get; init; }

    /// <summary>Gets the suggested tags for the article.</summary>
    public IReadOnlyList<string> SuggestedTags { get; init; } = [];

    /// <summary>Gets the suggested keywords for AI matching.</summary>
    public IReadOnlyList<string> SuggestedKeywords { get; init; } = [];

    /// <summary>Gets the related FAQs if requested.</summary>
    public IReadOnlyList<FaqSuggestion> RelatedFaqs { get; init; } = [];

    /// <summary>Gets the audit ID for feedback tracking.</summary>
    public Guid? AuditId { get; init; }

    /// <summary>Gets the number of tokens used.</summary>
    public int TokensUsed { get; init; }

    /// <summary>Gets the generation timestamp.</summary>
    public DateTime GeneratedAt { get; init; }
}

/// <summary>
/// A suggested FAQ entry extracted from conversations or generated by AI.
/// </summary>
public sealed record FaqSuggestion
{
    /// <summary>Gets the FAQ question.</summary>
    public string Question { get; init; } = string.Empty;

    /// <summary>Gets the FAQ answer.</summary>
    public string Answer { get; init; } = string.Empty;

    /// <summary>Gets the suggested category.</summary>
    public string? Category { get; init; }

    /// <summary>Gets the confidence score (0-100).</summary>
    public int Confidence { get; init; }

    /// <summary>Gets the source (e.g., "extracted_from_conversations", "ai_generated").</summary>
    public string Source { get; init; } = "ai_generated";
}

/// <summary>
/// Request for extracting FAQs from conversation history.
/// </summary>
public sealed record ExtractFaqsRequest
{
    /// <summary>Gets the number of days of conversations to analyze.</summary>
    public int DaysToAnalyze { get; init; } = 30;

    /// <summary>Gets the maximum number of FAQs to extract.</summary>
    public int MaxFaqs { get; init; } = 10;

    /// <summary>Gets the minimum confidence threshold (0-100).</summary>
    public int MinConfidence { get; init; } = 70;

    /// <summary>Gets optional category filter for conversations.</summary>
    public string? CategoryFilter { get; init; }
}

/// <summary>
/// Result of FAQ extraction from conversations.
/// </summary>
public sealed record ExtractFaqsResult
{
    /// <summary>Gets a value indicating whether the extraction was successful.</summary>
    public bool Success { get; init; }

    /// <summary>Gets the error message if extraction failed.</summary>
    public string? ErrorMessage { get; init; }

    /// <summary>Gets a value indicating whether the failure was due to usage limits.</summary>
    public bool LimitExceeded { get; init; }

    /// <summary>Gets the extracted FAQ suggestions.</summary>
    public IReadOnlyList<FaqSuggestion> Faqs { get; init; } = [];

    /// <summary>Gets the number of conversations analyzed.</summary>
    public int ConversationsAnalyzed { get; init; }

    /// <summary>Gets the audit ID for feedback tracking.</summary>
    public Guid? AuditId { get; init; }

    /// <summary>Gets the number of tokens used.</summary>
    public int TokensUsed { get; init; }

    /// <summary>Gets the extraction timestamp.</summary>
    public DateTime ExtractedAt { get; init; }
}

